"""Allow null secretname

Revision ID: 8b1cf009c01c
Revises: 1cfc2362b635
Create Date: 2025-10-10 10:25:54.374052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b1cf009c01c'
down_revision: Union[str, Sequence[str], None] = '1cfc2362b635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.alter_column('secret_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.alter_column('secret_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
