"""rename hero to user

Revision ID: cd77ebb8aa87
Revises: 8b1cf009c01c
Create Date: 2025-10-10 13:49:56.219166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd77ebb8aa87'
down_revision: Union[str, Sequence[str], None] = '8b1cf009c01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('hero', 'user')
    op.drop_index(op.f('ix_hero_age'), table_name='hero')
    op.drop_index(op.f('ix_hero_name'), table_name='hero')
    op.create_index(op.f('ix_user_age'), 'user', ['age'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'hero')
    op.drop_index(op.f('ix_user_age'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.create_index(op.f('ix_hero_age'), 'hero', ['age'], unique=False)
    op.create_index(op.f('ix_hero_name'), 'hero', ['name'], unique=True)
    # ### end Alembic commands ###