"""make team name unique

Revision ID: 54fb78171c67
Revises: cd77ebb8aa87
Create Date: 2025-10-10 15:27:48.679681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54fb78171c67'
down_revision: Union[str, Sequence[str], None] = 'cd77ebb8aa87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=False)
    # ### end Alembic commands ###
