"""delete unnecessary field in user table

Revision ID: 5b6e4ccd4d6b
Revises: 343974d01514
Create Date: 2025-10-23 00:21:39.700500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b6e4ccd4d6b'
down_revision: Union[str, Sequence[str], None] = '343974d01514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_age'), table_name='user')
    op.drop_column('user', 'secret_name')
    op.drop_column('user', 'age')
    op.drop_column('user', 'money')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('money', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('secret_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_age'), 'user', ['age'], unique=False)
    # ### end Alembic commands ###
