"""Add password field into hero table

Revision ID: 1cfc2362b635
Revises: e5bb31e0c269
Create Date: 2025-10-09 12:14:26.961870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1cfc2362b635'
down_revision: Union[str, Sequence[str], None] = 'e5bb31e0c269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), server_default="$argon2id$v=19$m=65536,t=3,p=4$2WtggtBQJ6eJhaRsOpod1A$lnQlBwgI47WvXZP0RUXEnhYkGouD1dEpwBpxjUb9veA", nullable=False))
    op.drop_index(op.f('ix_hero_name'), table_name='hero')
    op.create_index(op.f('ix_hero_name'), 'hero', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hero_name'), table_name='hero')
    op.create_index(op.f('ix_hero_name'), 'hero', ['name'], unique=False)
    op.drop_column('hero', 'hashed_password')
    # ### end Alembic commands ###
