"""add skill level to team table

Revision ID: e5bb31e0c269
Revises: 629974e48b8e
Create Date: 2025-10-07 04:22:52.160448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5bb31e0c269'
down_revision: Union[str, Sequence[str], None] = '629974e48b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('skill_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'skill_level')
    # ### end Alembic commands ###
